### ISSUE TITLE
The `Last-Modified` header is not stringified

### ISSUE THREAD

**Issue by radekmie** [vazco/meteor-universe-i18n#145]
There's a problem with the `Last-Modifed` header, that it's not stringified and therefore incorrectly formatted. What is more, as right now it's doing `toString()` on a `Date` object, in some cases (when `String(new Date())` contains a non-ASCII character, like `ś`) it may result in an error:

```
(node:6884) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR] [ERR_INVALID_CHAR]: Invalid character in header content ["Last-Modified"]
     at ServerResponse.setHeader (_http_outgoing.js:564:3)
     at setHeadersFromObject (~/.meteor/packages/webapp/.1.12.0.rmo20k.nmtj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:94:16)
     at ServerResponse.setWriteHeadHeaders (~/.meteor/packages/webapp/.1.12.0.rmo20k.nmtj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:122:5)
     at ServerResponse.writeHead (~/.meteor/packages/webapp/.1.12.0.rmo20k.nmtj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/on-headers/index.js:30:36)
     at packages/universe:i18n/source/server.ts:254:16
     at wrapper (packages/montiapm:agent/lib/hijack/wrap_webapp.js:179:36)
     at packages/montiapm:agent/lib/hijack/wrap_webapp.js:206:16
     at ~/.meteor/packages/promise/.0.12.0.107ja9q.iyqj++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 (node:6884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

The solution is simple: change [this](https://github.com/vazco/meteor-universe-i18n/blob/9cf2126a1e0f58a3102810ff32ced38fb9af522e/source/server.ts#L230) line to properly format the date, as the [documentation says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified).
```diff
-    'Last-Modified': cache.updatedAt,
+    'Last-Modified': cache.updatedAt.toGMTString(),
```

**Comment by radekmie** [comment]
It looks like it's our application -- we update the cache and leave the `Date` object there. Sorry for that!
