### ISSUE TITLE
An error is thrown when installing universe:i18n

### ISSUE THREAD

**Issue by dossorio** [vazco/meteor-universe-i18n#72]
Hi !

I am facing this exception:
```
Error: Extracted archive '/C/Users/DANIEL~1.OSS/AppData/Local/Temp/.tmp10ei1q2' should only contain one entry
    at Object.files.extractTarGz (C:\tools\fs\files.js:761:11)
    at Object.exports._extractAndConvert (C:\tools\packaging\tropohouse.js:50:9)
    at C:\tools\packaging\tropohouse.js:505:42
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\packaging\tropohouse.js:502:24
    at Array.forEach (native)

...
```

when running `meteor add universe:i18n`, do you have any clue about what could be happening ?

I am using `Windows 10` and `Meteor 1.5.1`

Many thanks !!!

**Comment by dossorio** [comment]
Closing this as the problem seems to have disappeared.

Removing folders in the pattern ` %USERPROFILE%/AppData/Local/Temp/.tmp*` could help, but it randomly got fixed in my case.
