### ISSUE TITLE
Not working with Meteor 1.4.4.2 - Error when starting server

### ISSUE THREAD

**Issue by raj-optisol** [vazco/meteor-universe-i18n#83]
Node v8.9.4
Npm 5.6.0
Meteor 1.4.4.2

Back trace:

=> Errors prevented startup:                  
   
   While loading plugin `UniverseI18n` from package `universe:i18n`:
   vm.js:24:10: Unexpected token ...
   at Object.exports.createScript (vm.js:24:10)
   at /tools/fs/files.js:1161:34
   at Function.time (/tools/tool-env/profile.js:305:10)
   at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
   at /tools/isobuild/bundler.js:1783:15
   at Array.forEach (native)
   at Function._.each._.forEach
   (/home/raj/.meteor/packages/meteor-tool/.1.4.4_2.aa4hbp.37kh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at JsImage.load (/tools/isobuild/bundler.js:1696:7)
   at /tools/isobuild/isopack.js:535:16
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/isopack.js:525:20
   at Function._.each._.forEach
   (/home/raj/.meteor/packages/meteor-tool/.1.4.4_2.aa4hbp.37kh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:513:7)
   at /tools/isobuild/compiler.js:382:16
   at Array.forEach (native)
   at /tools/isobuild/compiler.js:381:26
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at /tools/isobuild/compiler.js:377:16
   at /tools/isobuild/compiler.js:184:28
   at Object.withCache (/tools/fs/files.js:1652:12)
   at /tools/isobuild/compiler.js:183:11
   at Array.forEach (native)
   at Function._.each._.forEach
   (/home/raj/.meteor/packages/meteor-tool/.1.4.4_2.aa4hbp.37kh++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
   at Object.compile (/tools/isobuild/compiler.js:178:5)
   at /tools/isobuild/bundler.js:2738:24
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at bundle (/tools/isobuild/bundler.js:2681:31)
   at /tools/isobuild/bundler.js:2628:32
   at Object.withCache (/tools/fs/files.js:1652:12)
   at Object.exports.bundle (/tools/isobuild/bundler.js:2628:16)
   at /tools/runners/run-app.js:588:36
   at Function.run (/tools/tool-env/profile.js:490:12)
   at bundleApp (/tools/runners/run-app.js:587:34)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:631:35)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:890:28)
   at /tools/runners/run-app.js:417:12
   
   
=> Your application has errors. Waiting for file change.
=> A patch (Meteor 1.4.4.5) for your current release is available!

**Comment by cristo-rabani** [comment]
Hello,

Please use older version
